Repository FRONTENDSCHOOL10/Haemadi, pull requests merged in 2024-10, with the labels that each got.

#150 bugFix: 최종발표 때 발견한 오류들 수정
  netlify.toml
  src/pages/calendarPage/CalendarModal/CalendarModal.jsx
  src/pages/homePage/components/SelectEmotionModal/SelectEmotionModal.jsx
  src/pages/userInfoInputPage/components/KeywordInput/KeywordInput.module.css
  src/pages/userInfoInputPage/components/KeywordList/KeywordList.module.css
Labels: 🛠️ Refactor, 🐞 BugFix

#151 docs: README 작성 / bugFix: 몇가지 오류 수정
  README.md
  src/pages/calendarPage/Calendar/Calendar.module.css
  src/pages/calendarPage/CalendarPage.module.css
  src/pages/settingsPage/SettingsPage.module.css
  src/pages/settingsPage/components/ProfileSettingInfo/ProfileSettingInfo.jsx
  src/pages/settingsPage/components/ProfileSettingInfo/ProfileSettingInfo.module.css
  src/pages/settingsPage/index.jsx
  src/pages/signUpPage/index.jsx
  src/pages/userInfoInputPage/index.jsx
Labels: 📃 Docs, 🐞 BugFix

#156 feat: 404 페이지 제작
  public/logoItems/boat.webp
  public/logoItems/wave1.webp
  public/logoItems/wave2.webp
  public/logoItems/wave3.webp
  public/logoItems/wave4.webp
  src/pages/NotFoundPage/NotFoundPage.module.css
  src/pages/NotFoundPage/index.jsx
  src/router.jsx
Labels: ✨ Feat

#157 feat: Toast 수정
  src/components/ToasterProvider/ToasterProvider.jsx
  src/components/ToasterProvider/ToasterProvider.module.css
  src/stores/ToasterStore.js
Labels: ✨ Feat

#160 feat: SplashScreen 반응형
  public/bgImages/splash.webp
  public/bgImages/splashBg.webp
  public/bgImages/splash_desktop.webp
  public/logoItems/boat.webp
  public/logoItems/phoneMockUp.webp
  public/logoItems/wave1.webp
  public/logoItems/wave2.webp
  public/logoItems/wave3.webp
  public/logoItems/wave4.webp
  src/components/SplashScreen/SplashScreen.jsx
  src/components/SplashScreen/SplashScreen.module.css
  src/pages/NotFoundPage/NotFoundPage.module.css
  src/pages/NotFoundPage/index.jsx
Labels: 🛠️ Refactor, ✨ Feat

#161 feat: react-query 사용 및 조건부 redirect / bugFix: 전역 스타일 침범 수정 및 homePage의 모바일 디자인 오류 수정
  package.json
  pnpm-lock.yaml
  src/api/diaries.js
  src/api/replies.js
  src/main.jsx
  src/pages/calendarPage/index.jsx
  src/pages/homePage/components/Greeting/Greeting.module.css
  src/pages/homePage/index.jsx
  src/pages/letterBoxPage/index.jsx
  src/pages/pickUpBottlePage/components/BottleRadio/BottleRadio.module.css
  src/pages/pickUpBottlePage/index.jsx
  src/pages/selectReplyPage/components/ContentsRadioGroup/ContentsRadioGroup.jsx
  src/pages/selectReplyPage/components/ReplierRadioGroup/ReplierRadioGroup.jsx
  src/pages/settingsPage/SettingsPage.module.css
  src/pages/userInfoInputPage/index.jsx
  src/pages/writeDiaryPage/index.jsx
Labels: 🛠️ Refactor, ✨ Feat, 🐞 BugFix

#165 refactor: viewDiaryPage의 답장 컨텐츠 이미지를 아이콘으로 변경
  src/pages/viewDiaryPage/components/BookReply/BookReply.jsx
  src/pages/viewDiaryPage/components/MusicReply/MusicReply.jsx
  src/pages/viewDiaryPage/components/VideoReply/VideoReply.jsx
  src/pages/viewDiaryPage/index.jsx
Labels: 🛠️ Refactor
