Repository FRONTENDSCHOOL10/Haemadi, pull requests merged in 2024-09, with the labels that each got.

#5 init: Issue Template 생성
  .github/ISSUE_TEMPLATE/공통-이슈-템플릿.md
Labels: ⚙ Setting

#10 refactor: SVGIcon 리팩토링 및 png 수정
  public/sprites.svg
  src/components/SVGIcon/SVGIcon.jsx
  src/icons.js
Labels: 🛠️ Refactor

#12 design: 공통 스타일 설정
  src/styles/_theme.css
Labels: ⚙ Setting

#8 feat: Button 컴포넌트 추가
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
Labels: ✨ Feat

#16 feat: ModalDialog 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  src/components/ModalDialog/ModalDialog.jsx
  src/components/ModalDialog/ModalDialog.module.css
  src/main.jsx
Labels: ✨ Feat

#21 refactor: 1번째 멘토링 피드백 반영
  index.html
  public/favicon/favicon-16x16.png
  public/favicon/favicon-196x196.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-48x48.png
  public/favicon/favicon-64x64.png
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/SVGIcon/SVGIcon.jsx
  src/components/ShellButton/ShellButton.jsx
  src/styles/_base.css
  src/styles/_theme.css
  src/styles/main.css
Labels: 🛠️ Refactor

#15 feat: backButton 컴포넌트 제작
  src/components/BackButton/BackButton.jsx
  src/components/BackButton/BackButton.module.css
Labels: ✨ Feat

#20 feat: ContentTypeRadio 컴포넌트 제작
  public/sprites.svg
  src/@types/contentType.js
  src/@types/index.js
  src/constants.js
  src/icons.js
  src/pages/selectReply/components/ContentsRadio/ContentsRadio.jsx
  src/pages/selectReply/components/ContentsRadio/ContentsRadio.module.css
  src/pages/selectReply/components/ContentsRadioGroup/ContentsRadioGroup.jsx
  src/pages/selectReply/components/ContentsRadioGroup/ContentsRadioGroup.module.css
  src/pages/selectReply/index.jsx
  src/pages/selectReply/selectReply.module.css
Labels: ✨ Feat

#27 feat: 유저정보입력 - 건너뛰기 버튼 컴포넌트 제작
  src/pages/userInfoInput/components/SkipButton.jsx
  src/pages/userInfoInput/components/SkipButton.module.css
  src/pages/userInfoInput/index.jsx
  src/pages/userInfoInput/userInfoInput.module.css
Labels: ✨ Feat

#25 feat: 설정 - 기타 설정 항목 컴포넌트 제작
  public/sprites.svg
  src/icons.js
  src/pages/settings/components/OtherSettingPage/OtherSettingPage.jsx
  src/pages/settings/components/OtherSettingPage/OtherSettingPage.module.css
  src/pages/settings/index.jsx
  src/pages/settings/setting.module.css
Labels: ✨ Feat

#29 feat: PlusButton 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  public/sprites.svg
  src/constants.js
  src/icons.js
  src/pages/home/Home.module.css
  src/pages/home/components/PlusButton/PlusButton.jsx
  src/pages/home/components/PlusButton/PlusButton.module.css
  src/pages/home/index.jsx
Labels: ✨ Feat

#32 feat: ProgressBar 컴포넌트 제작
  src/pages/userInfoInput/components/ProgressBar/ProgressBar.jsx
  src/pages/userInfoInput/components/ProgressBar/ProgressBar.module.css
Labels: ✨ Feat

#34 feat: 유저정보입력 - KeywordList 컴포넌트 제작
  src/constants.js
  src/pages/userInfoInput/components/KeywordList/KeywordList.jsx
  src/pages/userInfoInput/components/KeywordList/KeywordList.module.css
  src/pages/userInfoInput/components/SkipButton/SkipButton.jsx
  src/pages/userInfoInput/components/SkipButton/SkipButton.module.css
Labels: ✨ Feat

#36 feat: 마이페이지 - InterestBadge
  src/pages/myPage/components/InterestBadge/InterestBadge.jsx
  src/pages/myPage/components/InterestBadge/InterestBadge.module.css
  src/pages/myPage/index.jsx
  src/pages/myPage/myPage.module.css
Labels: ✨ Feat

#40 feat: MusicReply 컴포넌트 제작
  public/sprites.svg
  src/icons.js
  src/pages/seeReply/components/MusicReply/MusicReply.jsx
  src/pages/seeReply/components/MusicReply/MusicReply.module.css
  src/pages/seeReply/index.jsx
  src/pages/seeReply/seeReply.module.css
Labels: ✨ Feat

#41 feat: BottleLink 컴포넌트 제작
  public/home/bottleLink_mailBox.png
  public/home/bottleLink_pickUp.png
  src/App.jsx
  src/constants.js
  src/pages/home/components/BottleLink/BottleLink.jsx
  src/pages/home/components/BottleLink/BottleLink.module.css
  src/pages/home/components/PlusButton/PlusButton.jsx
  src/pages/home/index.jsx
  src/stores/.gitkeep
  src/stores/mediaStore.js
Labels: 🛠️ Refactor, ✨ Feat

#38 feat: BottleRadio, BottleRadioGroup 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  public/sprites.svg
  src/components/SVGIcon/SVGIcon.jsx
  src/icons.js
  src/pages/pickUpBottle/components/BottleRadio/BottleRadio.jsx
  src/pages/pickUpBottle/components/BottleRadio/BottleRadio.module.css
  src/pages/pickUpBottle/components/BottleRadioGroup/BottleRadioGroup.jsx
  src/pages/pickUpBottle/components/BottleRadioGroup/BottleRadioGroup.module.css
  src/pages/pickUpBottle/index.jsx
  src/pages/pickUpBottle/pickUpBottle.module.css
Labels: ✨ Feat

#30 feat: Global Navigation(gnb) 컴포넌트 제작
  src/components/GNBLink/GNBLink.jsx
  src/components/GNBLink/GNBLink.module.css
  src/icons.js
Labels: ✨ Feat

#57 feat: AuthInput 컴포넌트 제작
  src/components/AuthInput/AuthInput.jsx
  src/components/AuthInput/AuthInput.module.css
Labels: ✨ Feat

#51 feat: StepIndicator 컴포넌트 제작
  src/pages/demoPage/components/ StepIndicator/StepIndicator.jsx
  src/pages/demoPage/components/ StepIndicator/StepIndicator.module.css
Labels: ✨ Feat

#46 feat: RadioInput 컴포넌트 제작
  src/components/RadioInput/RadioInput.jsx
  src/components/RadioInput/RadioInput.module.css
Labels: ✨ Feat

#59 feat: RadioList 컴포넌트 제작
  src/components/RadioList/RadioList.jsx
  src/components/RadioList/RadioList.module.css
Labels: ✨ Feat

#63 refactor: 2nd mentoring
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/components/ModalDialog/ModalDialog.jsx
  src/components/RadioList/RadioList.jsx
  src/components/ShellButton/ShellButton.jsx
  src/layouts/GlobalNav/GlobalNav.jsx
  src/pages/demoPage/components/StepIndicator/StepIndicator.jsx
  src/pages/demoPage/components/StepIndicator/StepIndicator.module.css
  src/pages/homePage/components/PlusButton/PlusButton.jsx
  src/pages/homePage/index.jsx
  src/pages/userInfoInputPage/components/KeywordInput/KeywordInput.jsx
  src/pages/userInfoInputPage/components/KeywordInput/KeywordInput.module.css
  src/pages/userInfoInputPage/components/KeywordList/KeywordList.jsx
  src/pages/userInfoInputPage/components/KeywordList/KeywordList.module.css
Labels: 🛠️ Refactor

#68 feat: 뮤직 remoteIcon 컴포넌트
  public/sprites.svg
  src/icons.js
  src/pages/musicPage/components/RemoteButton/RemoteButton.jsx
  src/pages/musicPage/components/RemoteButton/RemoteButton.module.css
Labels: ✨ Feat

#69 feat: music play time
  src/pages/musicPage/components/PlayTime/PlayTime.jsx
  src/pages/musicPage/components/PlayTime/PlayTime.module.css
Labels: ✨ Feat

#64 feat: pocket host crud
  src/api/.gitkeep
  src/api/diaries.js
  src/api/pbconfig.js
  src/api/users.js
  src/hooks/.gitkeep
  src/hooks/useFetch.js
Labels: ✨ Feat

#73 feat: MusicButton 컴포넌트 제작
  src/pages/musicPage/components/MusicButton/MusicButton.jsx
  src/pages/musicPage/components/MusicButton/MusicButton.module.css
Labels: ✨ Feat

#74 feat: OtherSettingList 컴포넌트 제작
  src/constants.js
  src/pages/settingsPage/components/OtherSettingButton/OtherSettingButton.jsx
  src/pages/settingsPage/components/OtherSettingButton/OtherSettingButton.module.css
  src/pages/settingsPage/components/OtherSettingList/OtherSettingList.jsx
  src/pages/settingsPage/components/OtherSettingList/OtherSettingList.module.css
Labels: ✨ Feat

#78 feat: Calender, CalenderModal 컴포넌트 및 CalendarPage 제작
  package.json
  pnpm-lock.yaml
  public/sprites.svg
  src/components/BackButton/BackButton.jsx
  src/components/ModalDialog/ModalDialog.jsx
  src/components/ShellButton/ShellButton.jsx
  src/icons.js
  src/pages/calendarPage/Calendar/Calendar.jsx
  src/pages/calendarPage/Calendar/Calendar.module.css
  src/pages/calendarPage/CalendarModal/CalendarModal.jsx
  src/pages/calendarPage/CalendarModal/CalendarModal.module.css
  src/pages/calendarPage/CalendarPage.module.css
  src/pages/calendarPage/index.jsx
  src/router.jsx
  src/utils/calendarList.js
  src/utils/index.js
Labels: 🛠️ Refactor, ✨ Feat

#84 feat: signupPage 제작
  public/sprites.svg
  src/App.jsx
  src/api/users.js
  src/assets/.gitkeep
  src/assets/background/background02.png
  src/components/BackButton/BackButton.jsx
  src/components/Button/Button.jsx
  src/components/ToasterProvider/ToasterProvider.jsx
  src/components/ToasterProvider/ToasterProvider.module.css
  src/hooks/useIsMounted.js
  src/icons.js
  src/pages/signUpPage/index.jsx
  src/pages/signUpPage/signUpPage.module.css
  src/stores/ToasterStore.js
  src/utils/index.js
  src/utils/jwt.js
  src/utils/storage.js
Labels: ✨ Feat, 📬 API

#89 feat: splashPage 제작 및 적용
  index.html
  public/splash.png
  public/splash_desktop.png
  src/App.jsx
  src/pages/splashPage/SplashPage.module.css
  src/pages/splashPage/index.jsx
Labels: ✨ Feat

#90 feat: demoPage 제작
  public/demoPage/demoPage_step1Bg.png
  public/demoPage/demoPage_step2Bg.png
  public/demoPage/demoPage_step3Bg.png
  src/components/Button/Button.module.css
  src/components/RadioInput/RadioInput.module.css
  src/components/RadioList/RadioList.jsx
  src/components/RadioList/RadioList.module.css
  src/pages/demoPage/DemoPage.module.css
  src/pages/demoPage/components/StepContents/Step1Content.jsx
  src/pages/demoPage/components/StepContents/Step2Content.jsx
  src/pages/demoPage/components/StepContents/Step2to2Content.jsx
  src/pages/demoPage/components/StepContents/Step3Content.jsx
  src/pages/demoPage/components/StepContents/StepContents.module.css
  src/pages/demoPage/components/StepIndicator/StepIndicator.jsx
  src/pages/demoPage/index.jsx
Labels: 🛠️ Refactor, ✨ Feat

#86 feat: homePage 1차 완성
  public/homePage/bottleLink_letterBox.png
  public/homePage/bottleLink_pickUp.png
  public/homePage/homePage_Bg.png
  public/homePage/homePage_darkBg.png
  public/sprites.svg
  src/components/ShellButton/ShellButton.jsx
  src/constants.js
  src/hooks/useBodyScrollLock.js
  src/layouts/GlobalNav/GlobalNav.jsx
  src/layouts/GlobalNav/GlobalNav.module.css
  src/layouts/RootLayout/RootLayout.jsx
  src/pages/homePage/HomePage.module.css
  src/pages/homePage/components/BottleLink/BottleLink.jsx
  src/pages/homePage/components/BottleLink/BottleLink.module.css
  src/pages/homePage/components/Greeting/Greeting.jsx
  src/pages/homePage/components/Greeting/Greeting.module.css
  src/pages/homePage/components/PlusButton/PlusButton.jsx
  src/pages/homePage/components/PlusButton/PlusButton.module.css
  src/pages/homePage/components/SelectEmotionModal/SelectEmotionModal.jsx
  src/pages/homePage/components/SelectEmotionModal/SelectEmotionModal.module.css
  src/pages/homePage/index.jsx
  src/router.jsx
  src/stores/sunStore.js
  src/styles/_base.css
Labels: 🛠️ Refactor, ✨ Feat

#83 feat:사용자 정보 입력 - 닉네임 Input + X 버튼 (reset 버튼)
  src/pages/userInfoInput/components/NickNameInput/NickNameInput.jsx
  src/pages/userInfoInput/components/NickNameInput/NickNameInput.module.css
Labels: 🛠️ Refactor, ✨ Feat

#100 feat: authStore 제작 및 비로그인 유저 리다이렉트 처리
  src/api/users.js
  src/components/BackButton/BackButton.jsx
  src/layouts/RootLayout/RootLayout.jsx
  src/pages/sendLetterPage/index.jsx
  src/pages/writeReplyPage/WriteReplyPage.module.css
  src/pages/writeReplyPage/index.jsx
  src/router.jsx
  src/stores/authStore.js
Labels: ✨ Feat, 📬 API

#92 feat: viewDairyPage 제작
  public/diaryBg.png
  src/hooks/useFetch.js
  src/pages/seeReplyPage/index.jsx
  src/pages/seeReplyPage/seeReplyPage.module.css
  src/pages/viewDiaryPage/ViewDiaryPage.module.css
  src/pages/viewDiaryPage/components/BookReply/BookReply.jsx
  src/pages/viewDiaryPage/components/BookReply/BookReply.module.css
  src/pages/viewDiaryPage/components/MusicReply/MusicReply.jsx
  src/pages/viewDiaryPage/components/MusicReply/MusicReply.module.css
  src/pages/viewDiaryPage/components/QuotesReply/QuotesReply.jsx
  src/pages/viewDiaryPage/components/QuotesReply/QuotesReply.module.css
  src/pages/viewDiaryPage/components/VideoReply/VideoReply.jsx
  src/pages/viewDiaryPage/components/VideoReply/VideoReply.module.css
  src/pages/viewDiaryPage/index.jsx
  src/pages/viewReply/index.jsx
  src/router.jsx
  src/utils/formatDate.js
  src/utils/index.js
Labels: 🛠️ Refactor, ✨ Feat

#96 feat: myPage 제작
  index.html
  package.json
  pnpm-lock.yaml
  src/api/users.js
  src/assets/background/background01.png
  src/assets/default_Profile.png
  src/icons.js
  src/pages/myPage/components/InterestBadge/InterestBadge.jsx
  src/pages/myPage/components/LinkButton/LinkButton.jsx
  src/pages/myPage/components/LinkButton/LinkButton.module.css
  src/pages/myPage/components/UserProfile/UserProfile.jsx
  src/pages/myPage/components/UserProfile/UserProfile.module.css
  src/pages/myPage/index.jsx
  src/pages/myPage/myPage.module.css
  src/pages/signUpPage/signUpPage.module.css
Labels: ✨ Feat

#121 feat: signInPage 제작
  src/pages/signInPage/index.jsx
Labels: ✨ Feat

#116 feat: letterBoxPage 제작
  src/pages/letterBoxPage/LetterBoxPage.module.css
  src/pages/letterBoxPage/index.jsx
  src/router.jsx
Labels: ✨ Feat

#122 feat: writeReplyPage 제작
  public/bgImages/sendingComplete_Bg.webp
  public/bgImages/sending_Bg.webp
  public/sendingScreen/letterBottle.webp
  src/api/replies.js
  src/components/ModalDialog/ModalDialog.module.css
  src/components/SendingScreen/SendingScreen.jsx
  src/components/SendingScreen/SendingScreen.module.css
  src/pages/writeReplyPage/WriteReplyPage.module.css
  src/pages/writeReplyPage/index.jsx
Labels: ✨ Feat

#114 feat: settingsPage 제작
  src/api/users.js
  src/pages/settingsPage/components/OtherSettingList/OtherSettingList.module.css
  src/pages/settingsPage/components/ProfileSettingInfo/ProfileSettingInfo.jsx
  src/pages/settingsPage/components/ProfileSettingInfo/ProfileSettingInfo.module.css
  src/pages/settingsPage/index.jsx
  src/pages/settingsPage/settingsPage.module.css
Labels: ✨ Feat

#128 feat: selctReplyPage에 SendingScreen 추가
  src/components/SendingCompleteScreen/SendingCompleteScreen.jsx
  src/components/SendingCompleteScreen/SendingCompleteScreen.module.css
  src/components/SendingScreen/SendingScreen.jsx
  src/pages/selectReplyPage/index.jsx
  src/pages/writeReplyPage/WriteReplyPage.module.css
  src/pages/writeReplyPage/index.jsx
Labels: 🛠️ Refactor, ✨ Feat

#134 feat: seoMetaData
  index.html
  public/fonts/NanumSquareB.woff2
  public/fonts/NanumSquareEB.woff2
  public/fonts/NanumSquareL.woff2
  public/fonts/NanumSquareR.woff2
  src/pages/authPage/index.jsx
  src/pages/calendarPage/index.jsx
  src/pages/demoPage/index.jsx
  src/pages/homePage/index.jsx
  src/pages/letterBoxPage/index.jsx
  src/pages/loadingPage/index.jsx
  src/pages/myPage/components/InterestBadge/InterestBadge.jsx
  src/pages/myPage/components/UserProfile/UserProfile.jsx
  src/pages/myPage/index.jsx
  src/pages/pickUpBottlePage/PickUpBottlePage.module.css
  src/pages/pickUpBottlePage/index.jsx
  src/pages/selectReplyPage/index.jsx
  src/pages/sendLetterPage/index.jsx
  src/pages/settingsPage/index.jsx
  src/pages/signInPage/index.jsx
  src/pages/signUpPage/index.jsx
  src/pages/statisticsPage/StatisticsPage.module.css
  src/pages/statisticsPage/index.jsx
  src/pages/userInfoInputPage/index.jsx
  src/pages/viewDiaryPage/index.jsx
  src/pages/viewLetterpage/index.jsx
  src/pages/writeDiaryPage/index.jsx
  src/pages/writeReplyPage/index.jsx
  src/router.jsx
Labels: ✨ Feat

#140 feat: gemini를 활용한 답장 제작
  package.json
  pnpm-lock.yaml
  src/api/gemini.js
  src/constants.js
  src/icons.js
  src/pages/selectReplyPage/components/ContentsRadioGroup/ContentsRadioGroup.jsx
  src/pages/selectReplyPage/index.jsx
  src/pages/viewDiaryPage/index.jsx
Labels: ✨ Feat, 📬 API

#142 refactor: statistics 계산 데이터 수정
  src/api/replies.js
  src/pages/calendarPage/index.jsx
  src/pages/signUpPage/index.jsx
  src/pages/statisticsPage/components/AIReplyType/AIReplyType.jsx
  src/pages/statisticsPage/components/EmotionPercentage/EmotionPercentage.jsx
  src/pages/statisticsPage/components/EmotionPercentage/EmotionPercentage.module.css
  src/pages/statisticsPage/components/ReplyFromPercentage/ReplyFromPercentage.jsx
  src/pages/statisticsPage/components/ReplyFromPercentage/ReplyFromPercentage.module.css
  src/pages/statisticsPage/index.jsx
  src/pages/userInfoInputPage/index.jsx
Labels: 🛠️ Refactor

#145 refactor: 종합 검토 및 수정
  src/components/AuthInput/AuthInput.jsx
  src/components/RadioInput/RadioInput.jsx
  src/components/RadioInput/RadioInput.module.css
  src/components/RadioList/RadioList.jsx
  src/components/ToasterProvider/ToasterProvider.jsx
  src/layouts/GlobalNav/GlobalNav.jsx
  src/pages/authPage/index.jsx
  src/pages/calendarPage/CalendarPage.module.css
  src/pages/calendarPage/index.jsx
  src/pages/demoPage/components/StepContents/Step1Content.jsx
  src/pages/demoPage/components/StepContents/Step2Content.jsx
  src/pages/demoPage/components/StepContents/Step2to2Content.jsx
  src/pages/demoPage/components/StepContents/Step3Content.jsx
  src/pages/demoPage/index.jsx
  src/pages/homePage/components/BottleLink/BottleLink.jsx
  src/pages/homePage/components/Greeting/Greeting.jsx
  src/pages/homePage/index.jsx
  src/pages/letterBoxPage/index.jsx
  src/pages/musicPage/index.jsx
  src/pages/myPage/index.jsx
  src/pages/pickUpBottlePage/components/BottleRadio/BottleRadio.jsx
  src/pages/selectReplyPage/SelectReplyPage.module.css
  src/pages/selectReplyPage/components/ContentsRadioGroup/ContentsRadioGroup.jsx
  src/pages/selectReplyPage/components/ReplierRadioGroup/ReplierRadioGroup.jsx
  src/pages/selectReplyPage/index.jsx
  src/pages/settingsPage/components/ProfileSettingInfo/ProfileSettingInfo.jsx
  src/pages/userInfoInputPage/UserInfoInputPage.module.css
  src/pages/userInfoInputPage/components/ProgressContents/ProgressContents.module.css
  src/pages/userInfoInputPage/components/ProgressContents/SetExperience.jsx
  src/pages/userInfoInputPage/index.jsx
  src/pages/viewDiaryPage/components/BookReply/BookReply.jsx
  src/pages/viewDiaryPage/components/QuotesReply/QuotesReply.jsx
  src/pages/viewDiaryPage/components/VideoReply/VideoReply.jsx
  src/pages/writeReplyPage/index.jsx
  src/router.jsx
Labels: 🛠️ Refactor, 🐞 BugFix
